import {
  mdiWhiteBalanceSunny,
  mdiWeatherCloudyArrowRight,
  mdiWeatherPartlyCloudy,
  mdiCloud,
  mdiWeatherRainy,
  mdiWeatherPouring,
  mdiWeatherLightningRainy,
  mdiWeatherHail,
  mdiSnowflakeAlert,
  mdiSnowman,
  mdiWeatherSnowyHeavy,
  mdiWeatherSnowyRainy,
  mdiWeatherFog,
  mdiFire,
  mdiHelpCircle,
} from '@mdi/js';
const weatherIconMap = new Map([
  ['100', { zh: '晴', en: 'Sunny' , icon: mdiWhiteBalanceSunny }],
  ['101', { zh: '多云', en: 'Cloudy', icon: mdiWhiteBalanceSunny }],
  ['102', { zh: '少云', en: 'Few Clouds', icon: mdiWeatherCloudyArrowRight }],
  ['103', { zh: '晴间多云', en: 'Partly Cloudy', icon: mdiWeatherPartlyCloudy }],
  ['104', { zh: '阴', en: 'Overcast', icon: mdiCloud }],
  ['150', { zh: '晴', en: 'Clear', icon: mdiWhiteBalanceSunny }],
  ['153', { zh: '晴间多云', en: 'Partly Cloudy', icon: mdiWeatherPartlyCloudy }],
  ['154', { zh: '阴', en: 'Overcast', icon: mdiCloud}],
  ['300', { zh: '阵雨', en: 'Shower Rain', icon: mdiWeatherRainy}],
  ['301', { zh: '强阵雨', en: 'Heavy Shower Rain', icon: mdiWeatherPouring}],
  ['302', { zh: '雷阵雨', en: 'Thundershower', icon: mdiWeatherLightningRainy}],
  ['303', { zh: '强雷阵雨', en: 'Heavy Thunderstorm', icon: mdiWeatherLightningRainy}],
  ['304', { zh: '雷阵雨伴有冰雹', en: 'Thundershower with hail', icon: mdiWeatherHail}],
  ['305', { zh: '小雨', en: 'Light Rain', icon: mdiWeatherRainy}],
  ['306', { zh: '中雨', en: 'Moderate Rain', icon: mdiWeatherPouring}],
  ['307', { zh: '大雨', en: 'Heavy Rain', icon: mdiWeatherPouring}],
  ['308', { zh: '极端降雨', en: 'Extreme Rain', icon: mdiWeatherPouring}],
  ['309', { zh: '毛毛雨/细雨', en: 'Drizzle Rain', icon: mdiWeatherRainy}],
  ['310', { zh: '暴雨', en: 'Storm', icon: mdiWeatherPouring}],
  ['311', { zh: '大暴雨', en: 'Heavy Storm', icon: mdiWeatherPouring}],
  ['312', { zh: '特大暴雨', en: 'Severe Storm', icon: mdiWeatherPouring}],
  ['313', { zh: '冻雨', en: 'Freezing Rain', icon: mdiSnowflakeAlert}],
  ['314', { zh: '小到中雨', en: 'Light to moderate rain', icon: mdiWeatherRainy}],
  ['315', { zh: '中到大雨', en: 'Moderate to heavy rain', icon: mdiWeatherPouring}],
  ['316', { zh: '大到暴雨', en: 'Heavy rain to storm', icon: mdiWeatherPouring}],
  ['317', { zh: '暴雨到大暴雨', en: 'Storm to heavy storm', icon: mdiWeatherPouring}],
  ['318', { zh: '大暴雨到特大暴雨', en: 'Heavy to severe storm', icon: mdiWeatherPouring}],
  ['399', { zh: '雨', en: 'Rain', icon: mdiWeatherRainy}],
  ['350', { zh: '阵雨', en: 'Shower Rain', icon: mdiWeatherRainy}],
  ['351', { zh: '强阵雨', en: 'Heavy Shower Rain', icon: mdiWeatherPouring}],
  ['400', { zh: '小雪', en: 'Light Snow', icon: mdiSnowman}],
  ['401', { zh: '中雪', en: 'Moderate Snow', icon: mdiSnowman}],
  ['402', { zh: '大雪', en: 'Heavy Snow', icon: mdiWeatherSnowyHeavy}],
  ['403', { zh: '暴雪', en: 'Snowstorm', icon: mdiWeatherSnowyHeavy}],
  ['404', { zh: '雨夹雪', en: 'Sleet', icon: mdiWeatherSnowyRainy}],
  ['405', { zh: '雨雪天气', en: 'Rain And Snow', icon: mdiWeatherSnowyRainy}],
  ['406', { zh: '阵雨夹雪', en: 'Shower Snow', icon: mdiWeatherSnowyRainy}],
  ['407', { zh: '阵雪', en: 'Snow Flurry', icon: mdiWeatherSnowyRainy}],
  ['408', { zh: '小到中雪', en: 'Light to moderate snow', icon: mdiSnowman}],
  ['409', { zh: '中到大雪', en: 'Moderate to heavy snow', icon: mdiWeatherSnowyHeavy}],
  ['410', { zh: '大到暴雪', en: 'Heavy snow to snowstorm', icon: mdiWeatherSnowyHeavy}],
  ['499', { zh: '雪', en: 'Snow', icon: mdiSnowman}],
  ['456', { zh: '阵雨夹雪', en: 'Shower Snow', icon: mdiWeatherSnowyRainy}],
  ['457', { zh: '阵雪', en: 'Snow Flurry', icon: mdiSnowman}],
  ['500', { zh: '薄雾', en: 'Mist', icon: mdiWeatherFog}],
  ['501', { zh: '雾', en: 'Foggy', icon: mdiWeatherFog}],
  ['502', { zh: '霾', en: 'Haze', icon: mdiWeatherFog}],
  ['503', { zh: '扬沙', en: 'Sand', icon: ''}],
  ['504', { zh: '浮尘', en: 'Dust', icon: ''}],
  ['507', { zh: '沙尘暴', en: 'Duststorm', icon: ''}],
  ['508', { zh: '强沙尘暴', en: 'Sandstorm', icon: ''}],
  ['509', { zh: '浓雾', en: 'Dense fog', icon: mdiWeatherFog}],
  ['510', { zh: '强浓雾', en: 'Strong fog', icon: mdiWeatherFog}],
  ['511', { zh: '中度霾', en: 'Moderate haze', icon: ''}],
  ['512', { zh: '重度霾', en: 'Heavy haze', icon: ''}],
  ['513', { zh: '严重霾', en: 'Severe haze', icon: ''}],
  ['514', { zh: '大雾', en: 'Heavy fog', icon: mdiWeatherFog}],
  ['515', { zh: '特强浓雾', en: 'Extra heavy fog', icon: mdiWeatherFog}],
  ['900', { zh: '热', en: 'Hot', icon: mdiFire}],
  ['901', { zh: '冷', en: 'Cold', icon: mdiSnowflakeAlert}],
  ['999', { zh: '未知', en: 'Unknown', icon: mdiHelpCircle}],
]);
export default weatherIconMap;
