const weatherIconMap = new Map([
  ['100', { zh: '晴', en: 'Sunny' , icon: 'mdi-white-balance-sunny' }],
  ['101', { zh: '多云', en: 'Cloudy', icon: 'mdi-weather-partly-cloudy' }],
  ['102', { zh: '少云', en: 'Few Clouds', icon: 'mdi-weather-cloudy-arrow-right' }],
  ['103', { zh: '晴间多云', en: 'Partly Cloudy', icon: 'mdi-weather-partly-cloudy' }],
  ['104', { zh: '阴', en: 'Overcast', icon: 'mdi-cloud' }],
  ['150', { zh: '晴', en: 'Clear', icon: 'md-white-balance-sunny' }],
  ['153', { zh: '晴间多云', en: 'Partly Cloudy', icon: 'mdi-weather-partly-cloudy' }],
  ['154', { zh: '阴', en: 'Overcast', icon: 'mdi-cloud'}],
  ['300', { zh: '阵雨', en: 'Shower Rain', icon: 'mdi-weather-rainy'}],
  ['301', { zh: '强阵雨', en: 'Heavy Shower Rain', icon: 'mdi-weather-pouring'}],
  ['302', { zh: '雷阵雨', en: 'Thundershower', icon: 'mdi-weather-lightning-rainy'}],
  ['303', { zh: '强雷阵雨', en: 'Heavy Thunderstorm', icon: 'mdi-weather-lightning-rainy'}],
  ['304', { zh: '雷阵雨伴有冰雹', en: 'Thundershower with hail', icon: 'mdi-weather-hail'}],
  ['305', { zh: '小雨', en: 'Light Rain', icon: 'mdi-weather-rainy'}],
  ['306', { zh: '中雨', en: 'Moderate Rain', icon: 'mdi-weather-pouring'}],
  ['307', { zh: '大雨', en: 'Heavy Rain', icon: 'mdi-weather-pouring'}],
  ['308', { zh: '极端降雨', en: 'Extreme Rain', icon: 'mdi-weather-pouring'}],
  ['309', { zh: '毛毛雨/细雨', en: 'Drizzle Rain', icon: 'mdi-weather-rainy'}],
  ['310', { zh: '暴雨', en: 'Storm', icon: 'mdi-weather-pouring'}],
  ['311', { zh: '大暴雨', en: 'Heavy Storm', icon: 'mdi-weather-pouring'}],
  ['312', { zh: '特大暴雨', en: 'Severe Storm', icon: 'mdi-weather-pouring'}],
  ['313', { zh: '冻雨', en: 'Freezing Rain', icon: 'mdi-snowflake-alert'}],
  ['314', { zh: '小到中雨', en: 'Light to moderate rain', icon: 'mdi-weather-rainy'}],
  ['315', { zh: '中到大雨', en: 'Moderate to heavy rain', icon: 'mdi-weather-pouring'}],
  ['316', { zh: '大到暴雨', en: 'Heavy rain to storm', icon: 'mdi-weather-pouring'}],
  ['317', { zh: '暴雨到大暴雨', en: 'Storm to heavy storm', icon: 'mdi-weather-pouring'}],
  ['318', { zh: '大暴雨到特大暴雨', en: 'Heavy to severe storm', icon: 'mdi-weather-pouring'}],
  ['399', { zh: '雨', en: 'Rain', icon: 'mdi-weather-rainy'}],
  ['350', { zh: '阵雨', en: 'Shower Rain', icon: 'mdi-weather-rainy'}],
  ['351', { zh: '强阵雨', en: 'Heavy Shower Rain', icon: 'mdi-weather-pouring'}],
  ['400', { zh: '小雪', en: 'Light Snow', icon: 'mdi-snowy'}],
  ['401', { zh: '中雪', en: 'Moderate Snow', icon: 'mdi-snowy'}],
  ['402', { zh: '大雪', en: 'Heavy Snow', icon: 'mdi-weather-snowy-heavy'}],
  ['403', { zh: '暴雪', en: 'Snowstorm', icon: 'mdi-weather-snowy-heavy'}],
  ['404', { zh: '雨夹雪', en: 'Sleet', icon: 'mdi-weather-snowy-rainy'}],
  ['405', { zh: '雨雪天气', en: 'Rain And Snow', icon: 'mdi-weather-snowy-rainy'}],
  ['406', { zh: '阵雨夹雪', en: 'Shower Snow', icon: 'mdi-weather-snowy-rainy'}],
  ['407', { zh: '阵雪', en: 'Snow Flurry', icon: 'mdi-weather-snowy-rainy'}],
  ['408', { zh: '小到中雪', en: 'Light to moderate snow', icon: 'mdi-snowy'}],
  ['409', { zh: '中到大雪', en: 'Moderate to heavy snow', icon: 'mdi-weather-snowy-heavy'}],
  ['410', { zh: '大到暴雪', en: 'Heavy snow to snowstorm', icon: 'mdi-weather-snowy-heavy'}],
  ['499', { zh: '雪', en: 'Snow', icon: 'mdi-snowy'}],
  ['456', { zh: '阵雨夹雪', en: 'Shower Snow', icon: 'mdi-weather-snowy-rainy'}],
  ['457', { zh: '阵雪', en: 'Snow Flurry', icon: 'mdi-snowy'}],
  ['500', { zh: '薄雾', en: 'Mist', icon: 'mdi-weather-fog'}],
  ['501', { zh: '雾', en: 'Foggy', icon: 'mdi-weather-fog'}],
  ['502', { zh: '霾', en: 'Haze', icon: 'mdi-weather-fog'}],
  ['503', { zh: '扬沙', en: 'Sand', icon: ''}],
  ['504', { zh: '浮尘', en: 'Dust', icon: ''}],
  ['507', { zh: '沙尘暴', en: 'Duststorm', icon: ''}],
  ['508', { zh: '强沙尘暴', en: 'Sandstorm', icon: ''}],
  ['509', { zh: '浓雾', en: 'Dense fog', icon: 'mdi-weather-fog'}],
  ['510', { zh: '强浓雾', en: 'Strong fog', icon: 'mdi-weather-fog'}],
  ['511', { zh: '中度霾', en: 'Moderate haze', icon: ''}],
  ['512', { zh: '重度霾', en: 'Heavy haze', icon: ''}],
  ['513', { zh: '严重霾', en: 'Severe haze', icon: ''}],
  ['514', { zh: '大雾', en: 'Heavy fog', icon: 'mdi-weather-fog'}],
  ['515', { zh: '特强浓雾', en: 'Extra heavy fog', icon: 'mdi-weather-fog'}],
  ['900', { zh: '热', en: 'Hot', icon: 'mdi-fire'}],
  ['901', { zh: '冷', en: 'Cold', icon: 'mdi-snowflake-alert'}],
  ['999', { zh: '未知', en: 'Unknown', icon: 'mdi-help-circle'}],
]);
export default weatherIconMap;
