const weatherIconMap = new Map([
  ['100', { zh: '晴', en: 'Sunny' , icon: 'mdi-white-balance-sunny'}],
  ['101', { zh: '多云', en: 'Cloudy', icon: 'mdi-cloud' }],
  ['102', { zh: '少云', en: 'Few Clouds', icon: 'mdi-weather-cloudy-arrow-right' }],
  ['103', { zh: '晴间多云', en: 'Partly Cloudy', icon: 'mdi-weather-partly-cloudy' }],
  ['104', { zh: '阴', en: 'Overcast' }],
  ['150', { zh: '晴', en: 'Clear' }],
  [153, { zh: '晴间多云', en: 'Partly Cloudy' }],
  [154, { zh: '阴', en: 'Overcast' }],
  [300, { zh: '阵雨', en: 'Shower Rain' }],
  [301, { zh: '强阵雨', en: 'Heavy Shower Rain' }],
  [302, { zh: '雷阵雨', en: 'Thundershower' }],
  [303, { zh: '强雷阵雨', en: 'Heavy Thunderstorm' }],
  [304, { zh: '雷阵雨伴有冰雹', en: 'Thundershower with hail' }],
  [305, { zh: '小雨', en: 'Light Rain' }],
  [306, { zh: '中雨', en: 'Moderate Rain' }],
  [307, { zh: '大雨', en: 'Heavy Rain' }],
  [308, { zh: '极端降雨', en: 'Extreme Rain' }],
  [309, { zh: '毛毛雨/细雨', en: 'Drizzle Rain' }],
  [310, { zh: '暴雨', en: 'Storm' }],
  [311, { zh: '大暴雨', en: 'Heavy Storm' }],
  [312, { zh: '特大暴雨', en: 'Severe Storm' }],
  [313, { zh: '冻雨', en: 'Freezing Rain' }],
  [314, { zh: '小到中雨', en: 'Light to moderate rain' }],
  [315, { zh: '中到大雨', en: 'Moderate to heavy rain' }],
  [316, { zh: '大到暴雨', en: 'Heavy rain to storm' }],
  [317, { zh: '暴雨到大暴雨', en: 'Storm to heavy storm' }],
  [318, { zh: '大暴雨到特大暴雨', en: 'Heavy to severe storm' }],
  [399, { zh: '雨', en: 'Rain' }],
  [350, { zh: '阵雨', en: 'Shower Rain' }],
  [351, { zh: '强阵雨', en: 'Heavy Shower Rain' }],
  [400, { zh: '小雪', en: 'Light Snow' }],
  [401, { zh: '中雪', en: 'Moderate Snow' }],
  [402, { zh: '大雪', en: 'Heavy Snow' }],
  [403, { zh: '暴雪', en: 'Snowstorm' }],
  [404, { zh: '雨夹雪', en: 'Sleet' }],
  [405, { zh: '雨雪天气', en: 'Rain And Snow' }],
  [406, { zh: '阵雨夹雪', en: 'Shower Snow' }],
  [407, { zh: '阵雪', en: 'Snow Flurry' }],
  [408, { zh: '小到中雪', en: 'Light to moderate snow' }],
  [409, { zh: '中到大雪', en: 'Moderate to heavy snow' }],
  [410, { zh: '大到暴雪', en: 'Heavy snow to snowstorm' }],
  [499, { zh: '雪', en: 'Snow' }],
  [456, { zh: '阵雨夹雪', en: 'Shower Snow' }],
  [457, { zh: '阵雪', en: 'Snow Flurry' }],
  [500, { zh: '薄雾', en: 'Mist' }],
  [501, { zh: '雾', en: 'Foggy' }],
  [502, { zh: '霾', en: 'Haze' }],
  [503, { zh: '扬沙', en: 'Sand' }],
  [504, { zh: '浮尘', en: 'Dust' }],
  [507, { zh: '沙尘暴', en: 'Duststorm' }],
  [508, { zh: '强沙尘暴', en: 'Sandstorm' }],
  [509, { zh: '浓雾', en: 'Dense fog' }],
  [510, { zh: '强浓雾', en: 'Strong fog' }],
  [511, { zh: '中度霾', en: 'Moderate haze' }],
  [512, { zh: '重度霾', en: 'Heavy haze' }],
  [513, { zh: '严重霾', en: 'Severe haze' }],
  [514, { zh: '大雾', en: 'Heavy fog' }],
  [515, { zh: '特强浓雾', en: 'Extra heavy fog' }],
  [900, { zh: '热', en: 'Hot' }],
  [901, { zh: '冷', en: 'Cold' }],
  [999, { zh: '未知', en: 'Unknown' }],
]);
export default weatherIconMap;
